displayName=Map Decorator
author=Tommy Turnip
description=Place objects and NPCs on any tile, animate, resize and share your scenes, client-side only
tags=map,object,npc,place,decorator,editor,poh,screenshot
version=1.1.0
plugins=com.tommyknight.mapdecorator.MapDecoratorPlugin
build=standard
